fix: validate group type/acronym properly in admin
painless-security/datatracker pull request #7
Opened 2022-06-07 18:06 UTC by jennifer-richards

Fixes #4028

2022-06-07 19:45 UTC, meadmaker requested changes

2022-06-07 19:45 UTC, meadmaker commented on ietf/group/admin.py
> +from django.core import validators
The tests seem to dislike you for this line.

2022-06-07 19:49 UTC, jennifer-richards commented on ietf/group/admin.py
> +from django.core import validators
Yep, removed.

2022-06-08 14:46 UTC, jennifer-richards commented
Fixed tests, closing and will commit upstream

2022-06-08 14:46 UTC, closed without merging